/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  allSidebar: [{type: 'autogenerated', dirName: '.'},{
    type: 'ref',
    id: "general/conflux-basics/what-is-conflux",
    label: "What is Conflux?"
  },],
  // Core: [
  //   {
  //     type: 'autogenerated',
  //     dirName: 'core',
  //   },
  //   // {
  //   //   type: 'category',
  //   //   label: 'Learn',
  //   //   link: {
  //   //     type: 'doc',
  //   //     id: 'core/learn/learn',
  //   //   },
  //   //   collapsed: false,
  //   //   items: [
  //   //     {
  //   //       type: 'autogenerated',
  //   //       dirName: 'core/learn',
  //   //     },
  //   //     // 添加更多 core/learn 下的文档
  //   //   ],
  //   // },
  //   // {
  //   //   type: 'category',
  //   //   label: 'Build',
  //   //   items: [
  //   //     {
  //   //       type: 'autogenerated',
  //   //       dirName: 'core/build',
  //   //     },
  //   //     // 添加更多 core/build 下的文档
  //   //   ],
  //   // },
  //   // 添加更多 core 下的类别和文档
  // ],
  // Espace: [
  //   'espace/espace',
  //   {
  //     type: 'category',
  //     label: 'Build',
  //     items: [
  //       'espace/build/cross-space-call',
  //       'espace/build/evm-compatibility',
  //       // 添加更多 espace/build 下的文档
  //     ],
  //   },
  //   // 添加更多 espace 下的类别和文档
  // ],
  // General: [
  //   'general/general',
  //   {
  //     type: 'category',
  //     label: 'Build',
  //     items: [
  //       'general/build/build',
  //       // 添加更多 general/build 下的文档
  //     ],
  //   },
  //   // 添加更多 general 下的类别和文档
  // ],
  concepts: [
    "general/article-collection-links/concept-links",
    {
      type: 'html',
      value: "<span class='menu__item'><b><medium> General </medium></b></span>"
    },
    {
      type: 'ref',
      id: "general/conflux-basics/what-is-conflux",
      label: "What is Conflux?"
    },
    {
      type: 'ref',
      id: "general/conflux-basics/spaces",
    },
    {
      type: 'ref',
      id: "general/conflux-basics/accounts",
    },
    {
      type: 'ref',
      id: "general/conflux-basics/transactions",
    },
    {
      type: 'ref',
      id: "general/conflux-basics/contracts",
    },
    {
      type: 'ref',
      id: "general/conflux-basics/gas",
    },
    {
      type: 'ref',
      id: "general/conflux-basics/wallets",
    },
    {
      type: 'ref',
      id: "general/conflux-basics/glossary",
    },
    {
      type: 'html',
      value: "<span class='menu__item'><b><medium> Core Space </medium></b></span>"
    },
    {
      type: 'ref',
      id: "core/learn/core-space-basics/accounts",
    },
    {
      type: 'ref',
      id: "core/learn/core-space-basics/addresses",
    },
    {
      type: 'ref',
      id: "core/learn/core-space-basics/sponsor-mechanism",
    },
    {
      type: 'ref',
      id: "core/learn/core-space-basics/storage",
    },
    {
      type: 'html',
      value: "<span class='menu__item'><b><medium> eSpace </medium></b></span>"
    },
    {
      type: 'ref',
      id: "espace/build/accounts",
    },
    // {
    //   type: 'autogenerated',
    //   dirName: 'core/learn/core-space-basics'
    // },
    // {
    //   type: 'autogenerated',
    //   dirName: 'espace/learn'
    // },
  ],
  tutorials: [
    {
      type: 'doc',
      id: 'general/article-collection-links/tutorial-links',
    },
    {
      type: 'html',
      value: "<span class='menu__item'><b><medium> User Guides </medium></b></span>"
    },
    {
      type: "category",
      label: "Wallets",
      link: {
        type: "doc",
        id: "general/tutorials/wallets/wallets"

      },
      items: [
        {
          type: "ref",
          id: 'general/tutorials/wallets/fluent',
        },
        {
          type: "ref",
          id: 'general/tutorials/wallets/fluent',
        },
      ]
    },
    // {
    //   type: 'autogenerated',
    //   dirName: 'general/tutorials'
    // },
    {
      type: 'html',
      value: "<span class='menu__item'><b><medium> Node Deployment </medium></b></span>"
    },
    "general/run-a-node/run-a-node",
    {
      type: 'html',
      value: "<span class='menu__item'><b><medium> Core Space Dev </medium></b></span>"
    },
    {
      type: 'autogenerated',
      dirName: 'core/tutorials'
    },
    {
      type: 'html',
      value: "<span class='menu__item'><b><medium> eSpace Dev </medium></b></span>"
    },
    {
      type: 'autogenerated',
      dirName: 'espace/tutorials'
    },
  ]

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};

module.exports = sidebars;
