name: "Bug / Typo / Mistake Report 报告BUG/笔误/事实性错误"
description: "Report a bug, typo, or incorrect information in the documentation 报告文档中的BUG/笔误/事实性错误"
labels: ["bug"]

body:
  # - type: markdown
  #   attributes:
  #     value: "We will reward contributors with FC for your valuablue feedback. Please join our [Dework space](https://app.dework.xyz/i/1fyrskMH16J8p2NcKX2uqX) and connect with your Github account if you are willing to receive FC rewards, in which case we could track your contribution history with ease."

  - type: textarea
    attributes:
      label: "Describe the issue 描述问题"
      description: "A clear and concise description of what the issue is."
      placeholder: "Describe the issue..."
    validations:
      required: true

  - type: input
    attributes:
      label: "Optional: Affected page(s) or section(s) 受影响的页面"
      description: "Please provide the URL(s) or the section(s) of the documentation affected by the issue."
      placeholder: "URL(s) or section(s)..."
    validations:
      required: false

  - type: textarea
    attributes:
      label: "Optional: Suggested solution 如何解决"
      description: "If you have a suggested solution or correction, please provide it here."
      placeholder: "Your suggested solution..."
    validations:
      required: false

  - type: textarea
    attributes:
      label: "Optional: Additional context 问题上下文信息"
      description: "Add any other context, screenshots, or relevant information about the issue."
      placeholder: "Additional context..."
    validations:
      required: false

  - type: checkboxes
    attributes:
      label: "Confirmation"
      description: "Check the box below if you'd be willing to fix this issue yourself within 2 months."
      options:
        - label: "I'd be willing to fix this issue myself within 2 months. 我将在两个月内自己修复这个问题。"
